Feature: Ristretto 255 Prime Order Group

Scenario: Should successfully generate a random group element
When a random group element is generated
Then the generated byte array is of the length for a group element
And the generated byte array contains non zero byte values

Scenario: Should successfully generate a random scalar value
When a random scalar value is generated
Then the generated byte array is of the length for a group element
And the generated byte array contains non zero byte values

Scenario: Should successfully perform Client Context Blinding - with Specification Test Vector 1
Given the values from Test Vector 1 in the specification
And the Client Context uses the Blind Random Scalar from the Test Vector
When the Client Context blinds the input
Then the Client Context blind result is correct

Scenario: Should successfully perform Client Context Blinding - with Specification Test Vector 2
Given the values from Test Vector 2 in the specification
And the Client Context uses the Blind Random Scalar from the Test Vector
When the Client Context blinds the input
Then the Client Context blind result is correct

Scenario: Should successfully perform Server Context Evaluation - with Specification Test Vector 1
Given the values from Test Vector 1 in the specification
When the Server Context performs evaluation
Then the Server Context evaluation result is correct

Scenario: Should successfully perform Server Context Evaluation - with Specification Test Vector 2
Given the values from Test Vector 2 in the specification
When the Server Context performs evaluation
Then the Server Context evaluation result is correct


# Scenario: 01 - Should register a client with a server
# Given the client with a username and password
# When the client registers with the server
# Then the client receives a session token from the server